// padrão
GET http://localhost:3003/
###
// filtro
GET http://localhost:3003/
###
// ordenação
GET http://localhost:3003/
###
// paginação
GET http://localhost:3003/
###
// todos juntos
GET http://localhost:3003/